### ISSUE TITLE
Can't install by default composer require nahid/apiz!

### ISSUE THREAD

**Issue by thearyanahmed** [nahid/apiz#10]
![image](https://user-images.githubusercontent.com/20617352/88761967-fe971a00-d191-11ea-97f4-0a72253580a6.png)

**Comment by me-shaon** [comment]
I just did a fresh install and it works fine. Maybe you're facing some issues due to the cache. Try deleting the composer cache and install it again. 
![image](https://user-images.githubusercontent.com/831997/88768446-ed9fd600-d19c-11ea-8f1a-cba2c9d176a7.png)

**Comment by nahid** [comment]
Maybe you have already installed v4.0-alpha, please remove it and reinstall.

**Comment by thearyanahmed** [comment]
Worked.
