### ISSUE TITLE
`setDefaultHeaders` returns [] without doing anything

### ISSUE THREAD

**Issue by ssi-anik** [nahid/apiz#3]
If I want to set my authorization token via https://github.com/nahid/apiz/blob/master/src/AbstractApi.php#L158 this method, it doesn't work.

**Comment by nahid** [comment]
please specify version and share your code.

**Comment by ssi-anik** [comment]
Version: `"nahid/apiz": "^1.1"`
Code:
```
$this->setDefaultHeaders(['authorization' => 'Bearer MyToKeN']);
$this->get($path);
```
The header is not passed.

**Comment by nahid** [comment]
it would be override

```php
protected function setDefaultHeaders()
{
    return [];
}
```
